### ISSUE TITLE
leadUserName is empty

### ISSUE THREAD

**Issue by Rafa40** [mrts/ask-jira#10]
Hi,

We have started using it to migrate information between JIRA instances and we think it is great!!!
But when using
def component(self, id):

All attributes are ok, except leadUserName which is always None.

Just for your information, I have seen JIRA REST API returns component lead information not as a simple field but as an structure...
[{"self":"https://jirainstance.dddd.com/rest/api/2/component/14223","id":"14223","name":"OKxxxxxxxxxxxxxx","description":"xxxxxxxxxxxxxxx ","lead":{"self":"https://jirainstance.dddd.com/rest/api/2/user?username=ASSDDD","key":"assddd","name":"ASSDDD","avatarUrls":{"16x16":" ...avatarId=10111"},"displayName":"User name","active":true},"assigneeType":"...

Please, could you check it?

Thank you in advnace.

**Comment by mrts** [comment]
That's quite a special case, sorry, I don't have time to cater for this... But please feel free to ask anyone who knows Python in your organization to submit a pull request.
