### ISSUE TITLE
AttributeError: type object 'PropertyHolder' has no attribute 'comment'

### ISSUE THREAD

**Issue by sk75** [mrts/ask-jira#15]
Very new to Jira & this library. And similarly a beginner in python.
I am trying a basic search.

issues = jira.search_issues(cfg.EpicSearch,maxResults=10000)
print(issues)
print  (issues[5])
print  (issues[5].fields.comment)

And getting the above error. Python version is 3.6.5 on windows10

**Comment by mrts** [comment]
Sorry, this does not relate to `ask-jira`. Please ask help from StackOverflow or `jira-python` support channels regarding this. Good luck :)!

**Comment by sk75** [comment]
thanks and sorry for the inconvenience.
