### ISSUE TITLE
Document README.md corrections

### ISSUE THREAD

**Issue by hpkkumar007** [mrts/ask-jira#3]
Thanks for the ask-jira.
Their seems an typo error in readme **Export/import**.

> **in exportimportconfig.py**
JIRA: As per code working this is a **Target** server configuration, but currently mentioned as Source

also please add a detail saying, Source Server Configuration will be picked from **jiraconfig.py**

Thanks & Regards,
KK

**Comment by mrts** [comment]
Thanks for the heads-up! Can you review pull request #4 and see if it looks better now?

**Comment by hpkkumar007** [comment]
Thanks for rapid response. Document changes seems fine in #4 & rest of the code changes you are expert in it :)

**Comment by mrts** [comment]
Thanks, merged :).
