### ISSUE TITLE
Ability to set a default user for moving tickets

### ISSUE THREAD

**Issue by mikevalstar** [mrts/ask-jira#5]
I have the problem that our JIRA is very old and we need to move historical tickets, so we would like to be able to set a default assignee for the user when there is not one in the list. Since this causes the job to abort

**Comment by mikevalstar** [comment]
This is a feature request BTW, if i get some free time i'll see about doing a pull request, but my python is very rusty.

**Comment by mrts** [comment]
Hi Mike!

Makes sense, please test if pull request #6 does what you want.

Best,
Mart

**Comment by mrts** [comment]
@mikevalstar ping :) - it would be much appreciated if you could test pull request #6 (and please ignore the ping freely if it is no longer relevant for you).

**Comment by mrts** [comment]
No response from reporter, closing.
