### ISSUE TITLE
Error:- AttributeError: type object 'PropertyHolder' has no attribute 'labels'

### ISSUE THREAD

**Issue by sahidulshaikh** [mrts/ask-jira#7]
Hello,
I am facing below error while running 'export_import_issues_for_jql'. 
Could you please help me how we can resolve this issue? 
=====================================================================
D:\jira-python\ask-jira>python ./ask-jira.py export_import_issues_for_jql "project = TMOVE AND issuetype not in subTaskIssueType
) AND issuetype != Epic ORDER BY key ASC"
About to export/import 50 issues
Exporting TMOVE-134 Traceback (most recent call last):
  File "./ask-jira.py", line 133, in <module>
    _main()
  File "./ask-jira.py", line 90, in _main
    command(jira, args)
  File "./ask-jira.py", line 59, in export_import_issues_for_jql
    exportimportconfig, args.jql)
  File "D:\jira-python\ask-jira\lib\export_import.py", line 15, in export_import_issues
    _make_new_issues(source_jira, target_jira, issues, conf, result, None)
  File "D:\jira-python\ask-jira\lib\export_import.py", line 24, in _make_new_issues
    fields = _get_new_issue_fields(issue.fields, conf)
  File "D:\jira-python\ask-jira\lib\export_import.py", line 66, in _get_new_issue_fields
    value = getattr(fields, name)
AttributeError: type object 'PropertyHolder' has no attribute 'labels'

===============================================================

Thanks,
Sahidul

**Comment by mrts** [comment]
Hello!

Interesting, it seems that the `labels` field is missing from JIRA response object. It should be present even if there are no labels. Can you list the available fields by adding `print(dir(fields))` to line 66 in `lib/export_import.py` and copy-pasting output here?

It may or may not be a bug in the `jira` library, can you try with

**Comment by mrts** [comment]
No response from reporter, closing.
